# RL^2 실험 환경 설정

# "dir" 또는 "vel" 중에 하나 선택 (str)
env_name: "dir"

# 저장할 실험 이름 (str)
save_exp_name: "exp_1"

# 저장할 파일 이름 (str or null)
save_file_name: null

# 불러올 실험 이름 (str or null)
load_exp_name: null

# 불러올 파일 이름 (str or null)
load_file_name: null

# 불러올 체크포인트 숫자 (int)
load_ckpt_num: 0

# GPU 인덱스 값 (int)
gpu_index: 0

# 랜덤 시드 값 (int)
seed: 0
